# Generated by Django 4.0.4 on 2022-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prioridade',
            field=models.TextField(default=''),
        ),
    ]
